# bitcoin network: mutinynet [custom signet]

services:
  bitcoind:
    container_name: mutinynet
    image: fedimint/mutinynet-bitcoind:master
    command: --rpcuser=bitcoin --rpcpassword=bitcoin -zmqpubrawblock=tcp://[::]:48332 -zmqpubrawtx=tcp://[::]:48333
    ports:
      - 0.0.0.0:38333:38333
      - 0.0.0.0:38332:38332
    volumes:
      - bitcoin_datadir:/root/.bitcoin
      - ${PWD}/fill-mempool.sh:/root/fill-mempool.sh
    networks:
      - dev-net
    restart: always
    platform: linux/amd64

# normal signet (needed to test fee estimation, kind of impossible to get signet coins)
#  bitcoind:
#    container_name: signet
#    image: dobtc/bitcoin:28.0
#    command: -signet --rpcuser=bitcoin --rpcpassword=bitcoin -rpcport=38332
#    ports:
#      - 0.0.0.0:38333:38333
#      - 0.0.0.0:38332:38332
#    volumes:
#      - bitcoin_datadir:/root/.bitcoin
#    networks:
#      - dev-net
#    restart: always
#    platform: linux/amd64

#  testnet 4 (not yet supported by CLN)
#  bitcoind:
#    container_name: testnet4
#    image: dobtc/bitcoin:28.0
#    command: --rpcuser=bitcoin --rpcpassword=bitcoin -testnet4 --rpcport=48332
#    ports:
#      - 0.0.0.0:48332:48332
#    volumes:
#      - bitcoin_datadir:/root/.bitcoin
#    networks:
#      - dev-net
#    restart: always
#    platform: linux/amd64

  lightningd:
    container_name: lightningd
    image: elementsproject/lightningd:latest
    volumes:
      - lightningd_datadir:/root/.lightning
      - bitcoin_datadir:/root/.bitcoin
      - ${PWD}/cln-config:/root/.lightning/config
      - ./plugins:/root/plugins
    environment:
      - NOSTR_RELAYS=wss://relay.damus.io,wss://relay.primal.net,wss://nos.lol
      - SWAP_FEE_PPM=10000
      - CONFIRMATION_TARGET_BLOCKS=6
      - FALLBACK_FEE_SATVB=65
      - PLUGIN_LOG_LEVEL=DEBUG
    networks:
      - dev-net
    platform: linux/amd64
    command: --network=signet


volumes:
  bitcoin_datadir:
    driver: local
  lightningd_datadir:
    driver: local

networks:
  dev-net:
    driver: bridge